"""Renders a commercialisation brief for a scored paper.

Analysis that lives only inside the app does not travel; this is the one-page
document a technology transfer officer can attach to an email.
"""

import re
from datetime import datetime
from typing import List, Optional

from ..agents.definitions import AGENTS, AGENTS_BY_NAME

_TAG = re.compile(r"<[^>]*>")


def _plain(value) -> str:
    """Strip markup from a PDF-metadata field.

    Title and author come straight out of the uploaded file, and the brief is
    meant to be emailed on. Markdown renderers that pass raw HTML through would
    otherwise carry an active payload from the PDF into the reader's viewer.
    """
    return _TAG.sub("", str(value or "")).replace("|", "\\|").strip()


def _display_score(agent: str, score: Optional[float]) -> Optional[float]:
    """Risk is stored as raw risk but always shown the same way up as the rest."""
    if score is None:
        return None
    spec = AGENTS_BY_NAME.get(agent)
    return 10 - score if (spec and spec["inverted"]) else score


def build_markdown(paper: dict, scores: List[dict], summary: Optional[dict],
                   prior_art: List[dict] = None) -> str:
    overall = (summary or {}).get("overall")
    verdict = (summary or {}).get("verdict") or "Not yet scored"
    by_agent = {s["agent"]: s for s in scores}

    heading = _plain(paper.get("title")) or _plain(paper.get("filename")) or "Untitled"
    lines = [
        f"# Commercialisation Brief: {heading}",
        "",
        f"**Overall score:** {overall if overall is not None else '—'} / 10  ",
        f"**Verdict:** {_plain(verdict)}  ",
    ]
    if paper.get("author"):
        lines.append(f"**Authors:** {_plain(paper['author'])}  ")
    lines += [
        f"**Pages:** {paper.get('page_count', '—')}  ",
        f"**Assessed:** {datetime.now().strftime('%Y-%m-%d %H:%M')}  ",
        "",
        "> Generated by ResearchLens using a local language model. Scores are"
        " decision support, not a substitute for professional patent or"
        " commercial advice.",
        "",
        "## Scores",
        "",
        "| Dimension | Score | Weight | Confidence |",
        "| --- | --- | --- | --- |",
    ]

    for spec in AGENTS:
        row = by_agent.get(spec["name"])
        shown = _display_score(spec["name"], (row or {}).get("score"))
        # A row can exist with a NULL score in a database written before scoring
        # was validated; render it as missing rather than crashing on format.
        if not row or shown is None:
            lines.append(f"| {spec['label']} | — | {int(spec['weight'] * 100)}% | — |")
            continue
        samples = row.get("samples") or 1
        if (samples > 1 and row.get("score_min") is not None
                and row.get("score_max") is not None):
            low = _display_score(spec["name"], row["score_max"])
            high = _display_score(spec["name"], row["score_min"])
            low, high = min(low, high), max(low, high)
            confidence = f"{low:.1f}–{high:.1f} over {samples} samples"
        else:
            confidence = "single pass"
        note = " *(inverted: lower risk scores higher)*" if spec["inverted"] else ""
        lines.append(
            f"| {spec['label']}{note} | **{shown:.1f}** | "
            f"{int(spec['weight'] * 100)}% | {confidence} |"
        )

    lines += ["", "## Assessment by dimension", ""]
    for spec in AGENTS:
        row = by_agent.get(spec["name"])
        shown = _display_score(spec["name"], (row or {}).get("score"))
        if not row or shown is None:
            continue
        lines += [f"### {spec['label']} — {shown:.1f}/10", "",
                  row.get("rationale") or "_No rationale recorded._", ""]

        if row.get("key_points"):
            lines.append("**Key points**")
            lines += [f"- {point}" for point in row["key_points"]]
            lines.append("")

        if row.get("evidence"):
            lines.append("**Evidence from the paper**")
            for quote in row["evidence"]:
                lines += [f"> {quote}", ""]

    if prior_art:
        lines += ["## Prior art", "",
                  "Similar published work retrieved from OpenAlex and used to"
                  " ground the patentability assessment.", "",
                  "| Work | Year | Venue | Citations |", "| --- | --- | --- | --- |"]
        for work in prior_art:
            title = work.get("title", "").replace("|", "\\|")
            if work.get("doi"):
                title = f"[{title}]({work['doi']})"
            venue = (work.get("venue") or "—").replace("|", "\\|")
            year = work.get("year") or "—"
            lines.append(
                f"| {title} | {year} | {venue} | {work.get('citations', 0)} |"
            )
        lines.append("")
    else:
        lines += ["## Prior art", "",
                  "_No prior-art records were retrieved for this paper._", ""]

    return "\n".join(lines)
